### ISSUE TITLE
OpenSSL 1.1.1

### ISSUE THREAD

**Issue by filom** [Frugghi/iSSH2#7]
I have issues compiling libssh for arm64, while armv7 is ok.

```
global.c:48:9: error: implicit declaration of function 'ENGINE_load_builtin_engines' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        libssh2_crypto_init();
        ^
../src/openssl.h:231:3: note: expanded from macro 'libssh2_crypto_init'
```

configuration: 
Libssh2 version: 1.8.0 (Automatically detected)
OpenSSL version: 1.1.1 (Automatically detected)
SDK version: 11.4 (Automatically detected)

All right with OpenSSL 1.1.0i.
Any ideas ?

**Comment by noefroidevaux** [comment]
I have the same problem (Libssh2 1.8.0, OpenSSL 1.1.1, iOS SDK 12.0), but it works with `./iSSH2.sh -o1.1.0i`

**Comment by Frugghi** [comment]
I'm not sure how to fix it, it seems that Libssh2 1.8.0 is not compatible with OpenSSL 1.1.1 or I'm not finding any flags/settings to make it working.

If you don't need OpenSSL 1.1.1, I'd follow @noefroidevaux suggestion to compile with OpenSSL 1.1.0i.

**Comment by yo-bur** [comment]
It might be worth making a note of this in the readme or automatically choosing `v1.1.0i`

**Comment by josuebg** [comment]
You can use OpenSSL 1.1.1 with libssh2 master branch. You can download it from snapshots: https://www.libssh2.org/snapshots/
You have to modify iSSH2-libssh2.sh so URL will be snapshots one and then use one snapshot version:
./iSSH2.sh -l 1.8.1-20190227

**Comment by manuelmuc** [comment]
You can use OpenSSL 1.1.1 with libssh2 master branch. You can download it from snapshots: https://www.libssh2.org/snapshots 
Just modify iSSH2-libssh2.sh so that it takes the url from snapshot and use one snapshot version:
./iSSH2.sh -l 1.8.1-20190227

**Comment by HongliYu** [comment]
`./iSSH2.sh -o1.1.0i` works for me

**Comment by Jan-E** [comment]
See https://github.com/Jan-E/iSSH2/commit/6b2b61d56fc43642980aacc529c9d9d14263cebf for a fix. Read the comment below the commit as well.

**Comment by Jan-E** [comment]
FWIW: with the commit at https://github.com/Jan-E/iSSH2/commit/6b2b61d56fc43642980aacc529c9d9d14263cebf updating to libssh2 1.8.2 with OpenSSL 1.1.1b was a breeze. Note the 'patching file src/openssl.h' after downloading libssh2:
```
TFRs-Mac:iSSH2 tfr$ ./iSSH2.sh --openssl=1.1.1b --libssh2=1.8.2
Initializing...

Libssh2 version: 1.8.2
OpenSSL version: 1.1.1b
SDK version: 12.2 (Automatically detected)
Architectures: armv7 armv7s arm64 x86_64
OS min version: 8.0

Downloading openssl-1.1.1b.tar.gz
######################################################################## 100.0%
MD5: 4532712e7bcc9414f5bce995e4e13930
Extracting openssl-1.1.1b.tar.gz
Building OpenSSL 1.1.1b, please wait...
- iPhoneOS armv7 done!
- iPhoneOS armv7s done!
- iPhoneOS arm64 done!
- iPhoneSimulator x86_64 done!
Building libssl.a fat library...
Building libcrypto.a fat library...
Copying headers...
Building done.
Downloading libssh2-1.8.2.tar.gz
######################################################################## 100.0%
MD5: 616efd99af3d9ef731a26bed6cee9593
Extracting libssh2-1.8.2.tar.gz
patching file src/openssl.h
Building Libssh2 1.8.2:
- iPhoneOS armv7 done!
- iPhoneOS armv7s done!
- iPhoneOS arm64 done!
- iPhoneSimulator x86_64 done!
Building libssh2.a fat library...
Copying headers...
Building done.
Cleaning up temporary files...
TFRs-Mac:iSSH2 tfr$ 

```

**Comment by Jan-E** [comment]
libssh2 1.9.0 was released. It compiles without additional testing.
Changelog: https://libssh2.org/changes.html#1.9.0

**Comment by filom** [comment]
Build are smooth and without any issue:
--
Libssh2 version: 1.9.0 (Automatically detected)
OpenSSL version: 1.1.1c (Automatically detected)
SDK version: 12.2 (Automatically detected)
[..]
Building done.
